# Generated by Django 6.0 on 2025-12-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_userprofile_spare_alter_rubric_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
    ]
