# Generated by Django 6.0 on 2025-12-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_add_is_active_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
