# Generated by Django 6.0 on 2025-12-22 12:15

import bboard.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0005_add_views_count_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(default=0, validators=[bboard.validators.MinMaxValueValidator(max_value=5, min_value=0)], verbose_name='Рейтинг'),
        ),
    ]
